use_frameworks!

platform :ios, '8.0'

target 'IndoorMapFramework_Example' do
  pod 'IndoorMapFramework', :path => '../'

  target 'IndoorMapFramework_Tests' do
    inherit! :search_paths

    
  end
end
